### ISSUE TITLE
Logout functionality

### ISSUE THREAD

**Issue by DamyanBG** [DamyanBG/cat-of-the-day-flask-api#1]
On /uploader/logout, /voter/logout implement log out functionality

**Comment by eduardonard** [comment]
Can i contribute to the project? Is still alive?

**Comment by DamyanBG** [comment]
Yes

**Comment by DamyanBG** [comment]
It is still alive and I have plans to deploy this project to end users. I was sick few weeks, then I broke my leg, for that the implementation was slow.

**Comment by eduardonard** [comment]
No worries, sorry about that. 
Can you write a readme.md? I want to help, idk what you mean with this issue. Are you talking about a route that logs you out?

**Comment by DamyanBG** [comment]
I was waiting for somebody to shows up. As far as I remember I implemented JWT token auth. The front end sends login request and back end generate JWT token, then it returns it to the front end. On the front end we build functionality with logout button, which will delete the token from the front end, send a request to the back end. So here is this functionality - a logic which handles request from logged in user, stores the token somewhere and that somewhere means if the back end receive again this token, it will not provide information, because the user logged out. 

I hope that make more sense.

**Comment by eduardonard** [comment]
I do know that my logic is quite different, but it could be safer for web-hacking _I think_.
[here](https://github.com/eduardonard/Calculators-PersonalFinance/blob/main/personalFinance/users/routes.py) you can see my flask app. take a look of the login and logout functions. What do you think about those? If you dont like them I'll go for your implementation

**Comment by DamyanBG** [comment]
I will take a look

**Comment by DamyanBG** [comment]
> I do know that my logic is quite different, but it could be safer for web-hacking _I think_.
> [here](https://github.com/eduardonard/Calculators-PersonalFinance/blob/main/personalFinance/users/routes.py) you can see my flask app. take a look of the login and logout functions. What do you think about those? If you dont like them I'll go for your implementation

Your Flask app is not RESTful

**Comment by DamyanBG** [comment]
I made that functionality.
